ame: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  test_1:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: '16'
    - name: Test with Maven
      run: mvn clean test
      
      
  test_2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: '16'
    - name: Test with Maven
      run: mvn clean test
    
    
    
